fix: python3 socket interaction expects bytes
Python3 socket sendall() and recv() expect bytes rather than
string. Collectd quagga module was failing on Focal hypervisors
with:

  File "/usr/share/collectd/python/quagga.py", line 66,
     in _query\n    sock.send("{}\0".format(query))"
  TypeError: a bytes-like object is required, not 'str'

Let's correctly send/receive bytes to Quagga/FRR socket and restore
respective metrics.

Related to [ch24481]